#!/usr/bin/env bash
# Run Nginx as Nginx

sudo sed -i 's/user www-date/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2100-fix_in_7_lines_or_les
sudo -u nginx service nginx restart
